
# This is a YAML file to install nginx onto oue web VM using YAML
---

- hosts: db

  gather_facts: yes
  # become root user
  become: true

  tasks:
  - name: install mongodb
    apt: pkg=mongodb state=present

  - name: Removing mongodb.conf file
    file:
      path: /etc/mongodb.conf
      state: absent


  - name: Create a file using touch give it 644 permission (u=rw)
    file:
      path: /etc/mongodb.conf
      state: touch
      mode: u=rw,g=r,o=r
      # User = read and write permission, group member = read,other = read

  - name: Insert multiple lines and Backup
    blockinfile:
      path: /etc/mongodb.conf
      block: |
        # mongodb.conf
        storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log

        # Connect through port 27017
        net:
          port: 27017
          bindIp: 0.0.0.0

  - name: restart mongodb
    become: true
    shell: systemctl restart mongodb

  # will hook the specified unit into relevant places,
  # so that it will automatically start on boot
  - name: enable mongodb
    become: true
    shell: systemctl enable mongodb

  # starts the mongodb on command
  - name: Start mongodb
    become: true
    shell: systemctl start mongodb

  - name: Check status
    become: true
    shell: systemctl status mongodb

