
# This is a YAML file to install nginx onto oue web VM using YAML
---

- hosts: db

  gather_facts: yes
  # become root user
  become: true

  tasks:
  - name: install mongodb
    apt: pkg=mongodb state=present

  - name: Removing mongodb.conf file
    file:
      path: /etc/mongodb.conf
      state: absent


  - name: Create a file using touch give it 644 permission (u=rw)
    file:
      path: /etc/mongodb.conf
      state: touch
      mode: u=rw,g=r,o=r
      # User = read and write permission, group member = read,other = read

  - name: Insert multiple lines and Backup
    blockinfile:
      path: /etc/mongodb.conf
      block: |
        # mongodb.conf
        storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log

        # Connect through port 27017
        net:
          port: 27017
          bindIp: 0.0.0.0

  - name: restart mongodb
    become: true
    shell: systemctl restart mongodb

  # will hook the specified unit into relevant places,
  # so that it will automatically start on boot
  - name: enable mongodb
    become: true
    shell: systemctl enable mongodb

  # starts the mongodb on command
  - name: Start mongodb
    become: true
    shell: systemctl start mongodb

  - name: Check status
    become: true
    shell: systemctl status mongodb

# where do we want to install
- hosts: web

# get the facts
  gather_facts: yes

# changes access to root user
  become: true

# what do we want ansible to do for us in the playbook
# In this case our only task is to install nginx

  tasks:
  - name: Install nginx
    apt: pkg=nginx state=present
    become_user: root

  - name: Remove nginx deafault file (delete file)
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      state: touch
      mode: '666'
      # Create new file and gives 666 permissions

  - name: Edit reverseproxy.conf to listen to port 80 via port 3000
    blockinfile:
      path: /etc/nginx/sites-enabled/reverseproxy.conf
      block: |
        server{
          listen 80;
          server_name development.local;
          location / {
              proxy_pass http://127.0.0.1:3000;
          }
        }

  - name: Create a symbolic link with reverseproxy.conf
    file:
      src: /etc/nginx/sites-enabled/reverseproxy.conf
      dest: /etc/nginx/sites-available/reverseproxy.conf
      state: link
  #  printf() function is used to print the (“character, string, float, integer, octal and hexadecimal values”) onto the output screen
  # tee is a command in command-line interpreters (shells) using standard streams which reads standard input and writes it to both
  # standard output and one or more files

 - name: nginx bug workaround
    shell: |
      sudo mkdir /etc/systemd/system/nginx.service.d
        printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" | \
          sudo tee /etc/systemd/system/nginx.service.d/override.conf
      sudo systemctl daemon-reload
      sudo systemctl restart nginx

  - name: Install nodejs
    apt: pkg=nodejs state=present

  - name: Install NPM
    apt: pkg=npm state=present

# Downloading pm2
  - name: Install pm2
    npm:
      name: pm2
      global: yes

  - name: download latest version of npm
    shell: |
      npm install -g npm@latest
      npm install mongoose -y

  # goes into app folder, seeds the database, kills any previous nodes, and start app.js
  - name: set up app
    shell: |
      cd app/
      npm install
      node seeds/seed.js
      pm2 kill
      pm2 start app.js
    environment:
      DB_HOST: mongodb://vagrant@192.168.33.11:27017/posts?authSource=admin
    become_user: root
